Fix connection leak when add_pool is called in rapid succession
inaka/Emysql pull request #15
Opened 2017-02-14 12:29 UTC by huss01

2017-02-14 12:29 UTC, elvisci commented on src/emysql.erl
>  %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result
Line 307 is too long: %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result.

2017-02-14 12:29 UTC, elvisci commented on src/emysql_conn.erl
>  	emysql_statements:remove(Conn#emysql_connection.id),
Line 313 has a tab at column 0.

2017-02-14 12:29 UTC, elvisci commented on src/emysql_conn.erl
>                      open_connections(Pool#pool{available = queue:in(Conn, Pool#pool.available)});
Line 172 is too long:                     open_connections(Pool#pool{available = queue:in(Conn, Pool#pool.available)});.

2017-02-14 12:29 UTC, elvisci commented on src/emysql_conn.erl
>  	%% garbage collect statements
Line 312 has a tab at column 0.

2017-02-14 12:52 UTC, elbrujohalcon requested changes

2017-02-14 12:52 UTC, elbrujohalcon commented on src/emysql.erl
> +            case catch emysql_conn_mgr:add_pool(Pool2) of
would you mind using `try…catch` instead of `case catch`?

2017-02-14 14:52 UTC, elvisci commented on src/emysql.erl
>  %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result
Line 304 is too long: %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result.

2017-02-14 14:54 UTC, elbrujohalcon approved these changes

2017-02-14 16:40 UTC, elvisci commented on src/emysql_conn.erl
>  	emysql_statements:remove(Conn#emysql_connection.id),
Line 313 has a tab at column 0.

2017-02-14 16:40 UTC, elvisci commented on src/emysql_conn.erl
>                      open_connections(Pool#pool{available = queue:in(Conn, Pool#pool.available)});
Line 172 is too long:                     open_connections(Pool#pool{available = queue:in(Conn, Pool#pool.available)});.

2017-02-14 16:40 UTC, elvisci commented on src/emysql_conn.erl
>  	%% garbage collect statements
Line 312 has a tab at column 0.

2017-02-14 16:40 UTC, elvisci commented on src/emysql.erl
>  %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result
Line 305 is too long: %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result.

2017-02-16 14:37 UTC, merged

2017-02-16 14:37 UTC, elvisci commented on src/emysql_conn.erl
>  	emysql_statements:remove(Conn#emysql_connection.id),
Line 313 has a tab at column 0.

2017-02-16 14:37 UTC, elvisci commented on src/emysql.erl
>  %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result
Line 305 is too long: %% @spec add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding) -> Result.

2017-02-16 14:37 UTC, elvisci commented on src/emysql_conn.erl
>  	%% garbage collect statements
Line 312 has a tab at column 0.

2017-02-16 14:37 UTC, elvisci commented on src/emysql_conn.erl
>                      open_connections(Pool#pool{available = queue:in(Conn, Pool#pool.available)});
Line 172 is too long:                     open_connections(Pool#pool{available = queue:in(Conn, Pool#pool.available)});.